export const SET_MAP_ORIGIN="SET_MAP_ORIGIN";
export const SET_MAP_ORIGIN_FLAG="SET_MAP_ORIGIN_FLAG";
export const SET_MAP_PIXELS="SET_MAP_PIXELS";

export const SET_MAP_DATA="SET_MAP_DATA"
export const SET_MAP_IS_SETSTAION="SET_MAP_IS_SETSTAION";
export const ADD_MAP_STATION="ADD_MAP_STATION";
export const SET_MAP_STATIONS="SET_MAP_STATIONS";

export const ADD_MAP_STATION_ORIENTATION="ADD_MAP_STATION_ORIENTATION";

export const SET_TEMP_STATION="SET_TEMP_STATION";
export const SET_TEMP_STATION_ORIENTATION="SET_TEMP_STATION_ORIENTATION"
export const SET_TEMP_STATION_NAME="SET_TEMP_STATION_NAME"

export const SET_COST_MAP_DATA="SET_COST_MAP_DATA"

export const SET_MAPPING_MAP="SET_MAPPING_MAP"